Update log.yml

diff --git a/.github/workflows/log.yml b/.github/workflows/log.yml
--- a/.github/workflows/log.yml
+++ b/.github/workflows/log.yml
@@ -1,1 +1,54 @@
+name: Typst document workflow
 
+on:
+  push:
+  workflow_dispatch:
+
+jobs:
+  common:
+    runs-on: ubuntu-latest
+    outputs:
+      FILE_PATH: '${{ steps.path.outputs.FILE_PATH }}'
+      FILE_NAME: '${{ steps.name.outputs.FILE_NAME }}'
+    steps:
+      - name: Set up Git repository
+        uses: actions/checkout@v4
+      - name: Get changed file
+        id: files
+        uses: tj-actions/changed-files@v40
+        with:
+          files: |
+             **.typ
+      - name: Extract path
+        id: path
+        run: |
+          FILES="${{ steps.files.outputs.all_changed_files }}"
+          echo "FILE_PATH=$(dirname "$FILES")" >> $GITHUB_OUTPUT
+      - name: Extract name w/o extension
+        id: name
+        run: |
+          FILES="${{ steps.files.outputs.all_changed_files }}"
+          echo "FILE_NAME=$(basename "${FILES}" .typ)" >> $GITHUB_OUTPUT
+      - name: Output to summary
+        run: |
+          echo "::notice::Modified files: ${{ steps.files.outputs.all_changed_files }}"
+          echo "::notice::Path: ${{ steps.path.outputs.FILE_PATH }}"
+          echo "::notice::File: ${{ steps.name.outputs.FILE_NAME }}"
+      - name: Check number of changed files
+        run: |
+          if [[ "${{ steps.path.outputs.FILE_PATH }}" == *".typ"* ]]; then
+            echo "::error::More than one Typst source have been modified. Aborting."
+            exit 1
+          fi
+  log:
+    runs-on: ubuntu-latest
+    needs: common
+    steps:
+      - name: Set up Git repository
+        uses: actions/checkout@v4
+      - name: python script
+        run: |
+          dir -l
+          
+    
+      
